### ISSUE TITLE
Can't create Function App when App service plan is EP1

### ISSUE THREAD

**Issue by tunglvNEV** [jaydesai-automate/terraform-azurerm-function-private-network#1]
I have trouble when ASP is EP1 It doesn't allow me to create Function App Linux.
Then I add:
app_settings = {
WEBSITE_CONTENTAZUREFILECONNECTIONSTRING = ConnectionStringOfStorageAccount
#AzureWebJobsStorage                      = azurerm_storage_account.storage_account_function.primary_connection_string
 #WEBSITE_CONTENTOVERVNET                  = 1
}
In this case, I successfully created Function App but could not deploy the source code, Storage Account d. With the error content is: "Azure Functions runtime is unreachable"

Thanks for your support!

**Comment by jaydesai-automate** [comment]
Under File share, you can try and create any 1 folder. This has worked for me before. Give it a shot and let me know if its works. 
Also, what are you using to deploy code, i want to test it out.

**Comment by tunglvNEV** [comment]
`## Private Linux Azure Function ##

##Function with Private Storage
##Creates A storage Account with 4 Endpoints
##Storage Account
resource "azurerm_storage_account" "storage_account_function" {
  name                            = var.func_app_storage_name
  resource_group_name             = var.resource_group_name
  location                        = var.location
  account_tier                    = "Standard"
  account_replication_type        = "LRS"
  allow_nested_items_to_be_public = false
  network_rules {
    default_action             = var.storage_account_networksetting
    ip_rules                   = []
    virtual_network_subnet_ids = [var.pep_subnet_id]
    bypass                     = ["AzureServices"]
  }
  tags = var.tags
}
resource "azurerm_storage_share" "storage_account_function-file_share" {
  name                 = "file-share-function"
  storage_account_name = azurerm_storage_account.storage_account_function.name
  quota                = 5120
  access_tier          = "TransactionOptimized"
}
##App Service Plan for functions##
#Linux
resource "azurerm_service_plan" "asp_funclnx" {
  name                         = var.func_asp_name
  resource_group_name          = var.resource_group_name
  location                     = var.location
  os_type                      = "Linux"
  maximum_elastic_worker_count = 20
  sku_name                     = var.sku_name
  tags                         = var.tags
}


resource "azurerm_private_endpoint" "st_pe" {
  count               = length(var.private_dns_zones)
  name                = "pep-${azurerm_storage_account.storage_account_function.name}-${var.private_dns_zones[count.index].subresource}"
  location            = var.location
  resource_group_name = var.resource_group_name
  subnet_id           = var.pep_subnet_id

  private_service_connection {
    name                           = "psc-${azurerm_storage_account.storage_account_function.name}-${var.private_dns_zones[count.index].subresource}"
    private_connection_resource_id = azurerm_storage_account.storage_account_function.id
    subresource_names              = ["${var.private_dns_zones[count.index].subresource}"]
    is_manual_connection           = false
  }
  private_dns_zone_group {
    name                 = "default"
    private_dns_zone_ids = [var.private_dns_zones[count.index].id]
  }
  tags = var.tags
  # depends_on = [
  #   azurerm_storage_account.storage_account_function,
  # ]
}

##Create Linux Function  
resource "azurerm_linux_function_app" "function" {
  name                = var.func_name
  resource_group_name = var.resource_group_name
  location            = var.location
  # service_plan_id      = var.azurerm_app_service_id
  service_plan_id               = azurerm_service_plan.asp_funclnx.id
  storage_account_name          = azurerm_storage_account.storage_account_function.name
  virtual_network_subnet_id     = var.integrate_subnet_id
  storage_uses_managed_identity = true
  identity {
    type = "SystemAssigned"
  }
  functions_extension_version = var.functions_extension_version

  site_config {
    application_stack {
      python_version = var.python_version
      dotnet_version = var.dotnet_version
      node_version   = var.node_version
    }
    application_insights_connection_string = var.application_insights_connection_string
    application_insights_key               = var.application_insights_key
    pre_warmed_instance_count              = 1
    # elastic_instance_minimum  = 2
    vnet_route_all_enabled           = true
    runtime_scale_monitoring_enabled = true
  }
  app_settings = {
    WEBSITE_CONTENTAZUREFILECONNECTIONSTRING = azurerm_storage_account.storage_account_function.primary_connection_string
    AzureWebJobsStorage                      = azurerm_storage_account.storage_account_function.primary_connection_string
    AzureWebJobsServiceBus                   = var.service_bus-connection_string
    WEBSITE_CONTENTOVERVNET                  = 1
    WEBSITE_CONTENTSHARE                     = azurerm_storage_share.storage_account_function-file_share.name
    WEBSITES_ENABLE_APP_SERVICE_STORAGE      = true
  }
  lifecycle {
    ignore_changes = [
      app_settings,
    tags]
  }
  tags = var.tags
}


##Function App Private End Point

resource "azurerm_private_endpoint" "pep_funcapp" {
  name                = "pep-${azurerm_linux_function_app.function.name}"
  location            = var.location
  resource_group_name = var.resource_group_name
  subnet_id           = var.pep_subnet_id
  private_service_connection {
    name                           = "psc-${azurerm_linux_function_app.function.name}"
    is_manual_connection           = false
    private_connection_resource_id = azurerm_linux_function_app.function.id
    subresource_names              = ["sites"]
  }
  private_dns_zone_group {
    name                 = "default"
    private_dns_zone_ids = [var.func_dns_id]
  }
  tags = var.tags
}

##Function  App Vnet intergration
# resource "azurerm_app_service_virtual_network_swift_connection" "netwrok_integration" {
#   app_service_id = azurerm_linux_function_app.function.id
#   subnet_id      = var.integrate_subnet_id
# }

##Function Diag Settings
resource "azurerm_monitor_diagnostic_setting" "diag_func" {
  name                       = "${var.func_name}-diagnostic"
  target_resource_id         = azurerm_linux_function_app.function.id
  log_analytics_workspace_id = var.log_analytics_ws_id

  log {
    category = "FunctionAppLogs"
  }
  metric {
    category = "AllMetrics"
  }
  lifecycle {
    ignore_changes = [log, metric]
  }
}
resource "azurerm_monitor_diagnostic_setting" "diag_asp" {
  name                       = "${azurerm_service_plan.asp_funclnx.name}-diagnostic"
  target_resource_id         = azurerm_service_plan.asp_funclnx.id
  log_analytics_workspace_id = var.log_analytics_ws_id

  metric {
    category = "AllMetrics"
  }
  lifecycle {
    ignore_changes = [log, metric]
  }
}



##RBAC Rights for Function to Storage Account

resource "azurerm_role_assignment" "functionToStorageDataContributor" {
  scope                = azurerm_storage_account.storage_account_function.id
  role_definition_name = "Storage Blob Data Contributor"
  principal_id         = azurerm_linux_function_app.function.identity[0].principal_id
}
resource "azurerm_role_assignment" "functionToContributor" {
  scope                = azurerm_storage_account.storage_account_function.id
  role_definition_name = "Contributor"
  principal_id         = azurerm_linux_function_app.function.identity[0].principal_id
}
resource "azurerm_role_assignment" "functionToStorageKeyOperator" {
  scope                = azurerm_storage_account.storage_account_function.id
  role_definition_name = "Storage Account Key Operator Service Role"
  principal_id         = azurerm_linux_function_app.function.identity[0].principal_id
}

resource "azurerm_role_assignment" "functionToStorageReaderDataAccess" {
  scope                = azurerm_storage_account.storage_account_function.id
  role_definition_name = "Reader and Data Access"
  principal_id         = azurerm_linux_function_app.function.identity[0].principal_id
}

`

**Comment by tunglvNEV** [comment]
I can't create file-share using terraform, because the storage account is private. The current workaround is to use the CLI to create the file-share. Any ideas on not using CLI?
Thank U @jaydesai-automate

**Comment by tunglvNEV** [comment]
Here is my code
```
resource "azurerm_storage_account" "storage_account_function" {
  name                            = var.func_app_storage_name
  resource_group_name             = var.resource_group_name
  location                        = var.location
  account_tier                    = "Standard"
  account_replication_type        = "LRS"
  allow_nested_items_to_be_public = false
  network_rules {
    default_action             = var.storage_account_networksetting
    ip_rules                   = []
    virtual_network_subnet_ids = [var.pep_subnet_id]
    bypass                     = ["AzureServices"]
  }
  tags = var.tags
}
resource "azurerm_storage_share" "storage_account_function-file_share" {
  name                 = "file-share-function"
  storage_account_name = azurerm_storage_account.storage_account_function.name
  quota                = 5120
  access_tier          = "TransactionOptimized"
}
##App Service Plan for functions##
#Linux
resource "azurerm_service_plan" "asp_funclnx" {
  name                         = var.func_asp_name
  resource_group_name          = var.resource_group_name
  location                     = var.location
  os_type                      = "Linux"
  maximum_elastic_worker_count = 20
  sku_name                     = var.sku_name
  tags                         = var.tags
}

resource "azurerm_private_endpoint" "st_pe" {
  count               = length(var.private_dns_zones)
  name                = "pep-${azurerm_storage_account.storage_account_function.name}-${var.private_dns_zones[count.index].subresource}"
  location            = var.location
  resource_group_name = var.resource_group_name
  subnet_id           = var.pep_subnet_id

  private_service_connection {
    name                           = "psc-${azurerm_storage_account.storage_account_function.name}-${var.private_dns_zones[count.index].subresource}"
    private_connection_resource_id = azurerm_storage_account.storage_account_function.id
    subresource_names              = ["${var.private_dns_zones[count.index].subresource}"]
    is_manual_connection           = false
  }
  private_dns_zone_group {
    name                 = "default"
    private_dns_zone_ids = [var.private_dns_zones[count.index].id]
  }
  tags = var.tags
}

##Create Linux Function  
resource "azurerm_linux_function_app" "function" {
  name                = var.func_name
  resource_group_name = var.resource_group_name
  location            = var.location
  service_plan_id               = azurerm_service_plan.asp_funclnx.id
  storage_account_name          = azurerm_storage_account.storage_account_function.name
  virtual_network_subnet_id     = var.integrate_subnet_id
  storage_uses_managed_identity = true
  identity {
    type = "SystemAssigned"
  }
  functions_extension_version = var.functions_extension_version

  site_config {
    application_stack {
      python_version = var.python_version
      dotnet_version = var.dotnet_version
      node_version   = var.node_version
    }
    application_insights_connection_string = var.application_insights_connection_string
    application_insights_key               = var.application_insights_key
    pre_warmed_instance_count              = 1
    # elastic_instance_minimum  = 2
    vnet_route_all_enabled           = true
    runtime_scale_monitoring_enabled = true
  }
  app_settings = {
    WEBSITE_CONTENTAZUREFILECONNECTIONSTRING = azurerm_storage_account.storage_account_function.primary_connection_string
    AzureWebJobsStorage                      = azurerm_storage_account.storage_account_function.primary_connection_string
    AzureWebJobsServiceBus                   = var.service_bus-connection_string
    WEBSITE_CONTENTOVERVNET                  = 1
    WEBSITE_CONTENTSHARE                     = azurerm_storage_share.storage_account_function-file_share.name
    WEBSITES_ENABLE_APP_SERVICE_STORAGE      = true
    EmailStorageConnectionString = var.email_storage-connection_string
    EmailDataLakeConnectionString = var.email_datalake-connection_string
    DWHConnectionString = var.dwh-connection_string
  }
  lifecycle {
    ignore_changes = [
      app_settings,
    tags]
  }
  tags = var.tags
}
```

**Comment by jaydesai-automate** [comment]
I am not sure why it would not work, is it a rights issue? It's still a storage account that you can manage. Try creating the share before the Function. Here is what i use and it works.

resource "azurerm_storage_share" "fileshare" {
  name                 = "func-xxxxx-001"
  storage_account_name = "storage account"
  quota                = 5120
  enabled_protocol     = "SMB"
}

**Comment by tunglvNEV** [comment]
I have solved the problem. This is the same [problem.](https://codeutility.org/terraform-error-on-adding-a-storage-share-to-the-azure-storage-account-stack-overflow/)
I have to create file-share before setting up network private for storage

```
resource "azurerm_storage_account" "storage_account_function" {
  name                            = var.func_app_storage_name
  resource_group_name             = var.resource_group_name
  location                        = var.location
  account_tier                    = "Standard"
  account_replication_type        = "LRS"
  allow_nested_items_to_be_public = false
  tags = var.tags
}
resource "azurerm_storage_share" "storage_account_function-file_share" {
  name                 = "file-share-function"
  storage_account_name = azurerm_storage_account.storage_account_function.name
  quota                = 5120
  access_tier          = "TransactionOptimized"
}
resource "azurerm_storage_account_network_rules" "storage_account_function-network" {
  storage_account_id = azurerm_storage_account.storage_account_function.id

  default_action             = var.storage_account_networksetting
  ip_rules                   = []
  virtual_network_subnet_ids = [var.pep_subnet_id]
  bypass                     = ["AzureServices"]
  depends_on = [
    azurerm_storage_share.storage_account_function-file_share,
  ]
}
```

**Comment by jaydesai-automate** [comment]
Thanks for the follow up! Thanks
